"""empty message

Revision ID: 1636e56777fa
Revises: 9debb5c4b2c9
Create Date: 2019-12-12 11:23:35.557445

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1636e56777fa'
down_revision = '9debb5c4b2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('message', sa.String(), nullable=True))
    op.alter_column('bookings', 'finish',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'finish',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('bookings', 'message')
    # ### end Alembic commands ###
