"""empty message

Revision ID: 25d1926a76ee
Revises: 2c5910afd622
Create Date: 2019-12-06 11:31:46.820647

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '25d1926a76ee'
down_revision = '2c5910afd622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_sitter', sa.Boolean(), nullable=True))
    op.drop_constraint('users_sitter_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'sitter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sitter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_sitter_id_fkey', 'users', 'sitter', ['sitter_id'], ['id'])
    op.drop_column('users', 'is_sitter')
    # ### end Alembic commands ###
