"""empty message

Revision ID: 691208326272
Revises: f97fa2b525b1
Create Date: 2019-12-04 15:23:18.533158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691208326272'
down_revision = 'f97fa2b525b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
