"""empty message

Revision ID: 692922c6675a
Revises: c75e546a2bf4
Create Date: 2019-12-06 11:19:32.675016

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '692922c6675a'
down_revision = 'c75e546a2bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitter', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sitter', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sitter', type_='foreignkey')
    op.drop_column('sitter', 'user_id')
    # ### end Alembic commands ###
