"""empty message

Revision ID: 93aa6b7b3015
Revises: 0338c59eeeb7
Create Date: 2019-12-06 00:10:39.655441

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '93aa6b7b3015'
down_revision = '0338c59eeeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('sitter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sitter', ['sitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sitter_id')
    op.drop_table('sitter')
    # ### end Alembic commands ###
