"""empty message

Revision ID: c75e546a2bf4
Revises: 93aa6b7b3015
Create Date: 2019-12-06 11:15:16.954112

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c75e546a2bf4'
down_revision = '93aa6b7b3015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitter', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitter', 'picture')
    # ### end Alembic commands ###
