"""empty message

Revision ID: e835285fd840
Revises: ec9dc322dd71
Create Date: 2019-12-12 00:19:18.690299

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e835285fd840'
down_revision = 'ec9dc322dd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('finish', sa.DateTime(), nullable=True))
    op.add_column('booking', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('booking', sa.Column('total_price', sa.Integer(), nullable=True))
    op.drop_column('booking', 'check_in')
    op.drop_column('booking', 'drop_off')
    op.drop_column('booking', 'check_out')
    op.drop_column('booking', 'pick_up')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('pick_up', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('drop_off', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'total_price')
    op.drop_column('booking', 'start')
    op.drop_column('booking', 'finish')
    # ### end Alembic commands ###
