"""empty message

Revision ID: f0e418b2b58e
Revises: 305d07707254
Create Date: 2019-12-15 23:51:21.989331

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f0e418b2b58e'
down_revision = '305d07707254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
